// <auto-generated />
using System;
using Delivery_app.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Delivery_app.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Delivery_app.Entities.Admin", b =>
                {
                    b.Property<int>("admin_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(25)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(25)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("password_salt")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("admin_id");

                    b.ToTable("admins");
                });

            modelBuilder.Entity("Delivery_app.Entities.Couriers", b =>
                {
                    b.Property<int>("courier_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("commission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double")
                        .HasDefaultValue(0.80000000000000004);

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("disable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("email")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("name")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<bool?>("onBoard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("otp")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("password_salt")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("phone_num")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("profile_picture")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("vehicle_plate_no")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<byte>("vehicle_type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("courier_id");

                    b.ToTable("couriers");
                });

            modelBuilder.Entity("Delivery_app.Entities.Documents", b =>
                {
                    b.Property<int>("document_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("courier_id")
                        .HasColumnType("int");

                    b.Property<string>("document")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("document_id");

                    b.HasIndex("courier_id");

                    b.ToTable("documents");
                });

            modelBuilder.Entity("Delivery_app.Entities.DropPoints", b =>
                {
                    b.Property<int>("drop_point_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("comment")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("contact_num")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("latitude")
                        .HasColumnType("FLOAT(10, 6)");

                    b.Property<float>("longitude")
                        .HasColumnType("FLOAT(10, 6)");

                    b.Property<int>("order_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("drop_point_id");

                    b.HasIndex("order_id");

                    b.ToTable("drop_points");
                });

            modelBuilder.Entity("Delivery_app.Entities.Orders", b =>
                {
                    b.Property<int>("order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("contact_num")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("courier_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("delivery_status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<float>("latitude")
                        .HasColumnType("FLOAT(10, 6)");

                    b.Property<float>("longitude")
                        .HasColumnType("FLOAT(10, 6)");

                    b.Property<string>("name")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<bool>("notify_recipient")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("notify_sender")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("pick_up_address")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("pick_up_datetime")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("price")
                        .HasColumnType("double");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<byte>("vehicle_type")
                        .HasColumnType("tinyint unsigned");

                    b.Property<double>("weight")
                        .HasColumnType("double");

                    b.HasKey("order_id");

                    b.HasIndex("user_id");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("Delivery_app.Entities.Payments", b =>
                {
                    b.Property<int>("payment_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("amount")
                        .HasColumnType("double");

                    b.Property<int>("courier_id")
                        .HasColumnType("int");

                    b.Property<double>("courier_pay")
                        .HasColumnType("double");

                    b.Property<byte>("courier_payment_status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("order_id")
                        .HasColumnType("int");

                    b.Property<byte>("order_status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("payment_method")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("payment_id");

                    b.HasIndex("courier_id");

                    b.HasIndex("order_id")
                        .IsUnique();

                    b.HasIndex("user_id");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("Delivery_app.Entities.PromoCodes", b =>
                {
                    b.Property<int>("promo_code_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("discount")
                        .HasColumnType("double");

                    b.Property<byte>("discount_type")
                        .HasColumnType("tinyint unsigned");

                    b.Property<double>("minimum_spend")
                        .HasColumnType("double");

                    b.Property<string>("name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("num_claim_per_user")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("validity")
                        .HasColumnType("datetime(6)");

                    b.HasKey("promo_code_id");

                    b.ToTable("promo_codes");
                });

            modelBuilder.Entity("Delivery_app.Entities.Users", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("fcm_token")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("locked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("name")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("password")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("password_salt")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("phone_num")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("user_type")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("user_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Delivery_app.Entities.Documents", b =>
                {
                    b.HasOne("Delivery_app.Entities.Couriers", null)
                        .WithMany("documents")
                        .HasForeignKey("courier_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Delivery_app.Entities.DropPoints", b =>
                {
                    b.HasOne("Delivery_app.Entities.Orders", null)
                        .WithMany("drop_points")
                        .HasForeignKey("order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Delivery_app.Entities.Orders", b =>
                {
                    b.HasOne("Delivery_app.Entities.Users", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Delivery_app.Entities.Payments", b =>
                {
                    b.HasOne("Delivery_app.Entities.Couriers", "courier")
                        .WithMany()
                        .HasForeignKey("courier_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Delivery_app.Entities.Orders", "order")
                        .WithOne()
                        .HasForeignKey("Delivery_app.Entities.Payments", "order_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Delivery_app.Entities.Users", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
